#!/bin/bash

count=1
if [ -z "$2" ]
then
    count=1
else
    count=$2
fi

extra="$(($count-1))"
echo Running $count curls
for ((i=1;i<=$extra;i++)); do
    curl -s -o /dev/null $1 > /dev/null&
done
curl -s -w 'Testing Website Response Time for: %{url_effective}\n\nLookup Time:\t\t%{time_namelookup}\nConnect Time:\t\t%{time_connect}\nPre-transfer Time:\t%{time_pretransfer}\nStart-transfer Time:\t%{time_starttransfer}\n\nTotal Time:\t\t%{time_total}\n' -o /dev/null $1 | tee webspeedtest_"$(date)"
